MvcNetCorePrcaticaEmpleadosRegistro/Models/Departamento.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcNetCorePrcaticaEmpleadosRegistro.Models
{
    
    [Table("DEPT")]
    public class Departamento
    {
        [Key]
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }
        [Column("DNOMBRE")]
        public string Nombre { get; set; }
        [Column("LOC")]
        public string Localidad { get; set; }
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Models/Empleado.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcNetCorePrcaticaEmpleadosRegistro.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("OFICIO")]
        public string Oficio { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("DEPT_NO")]
        public int IdDepartamento { get; set; }
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Models/ErrorViewModel.cs
namespace MvcNetCorePrcaticaEmpleadosRegistro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Models/ModelEmpleadosDepartamento.cs
namespace MvcNetCorePrcaticaEmpleadosRegistro.Models
{
    public class ModelEmpleadosDepartamento
    {
        public Departamento Departamento { get; set; }
        public List<Empleado> Empleado { get; set; }
        public int NumeroRegistros { get; set; }
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcNetCorePrcaticaEmpleadosRegistro.Models;

namespace MvcNetCorePrcaticaEmpleadosRegistro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Controllers/PracticaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using MvcNetCorePrcaticaEmpleadosRegistro.Models;
using MvcNetCorePrcaticaEmpleadosRegistro.Repositories;

namespace MvcNetCorePrcaticaEmpleadosRegistro.Controllers
{
    public class PracticaController : Controller
    {
        private RepositoryHospital repo;

        public PracticaController(RepositoryHospital repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Departamento> d = await this.repo.GetDepartamentosAsync();
            return View(d);
        }

        public async Task<IActionResult> Details(int? posicion, int idDepartamento)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            ModelEmpleadosDepartamento model = await this.repo.GetEmpleadosDepartamentoOutAsync(posicion.Value, idDepartamento);
            ViewData["REGISTROS"] = model.NumeroRegistros;
            ViewData["POSICION"] = posicion;
            int siguiente = posicion.Value + 1;
            if (siguiente > model.NumeroRegistros)
            {
                siguiente = model.NumeroRegistros;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ULTIMO"] = model.NumeroRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["DEPARTAMENTO"] = model.Departamento.IdDepartamento;
            return View(model);
        }
    }
}

MvcNetCorePrcaticaEmpleadosRegistro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCorePrcaticaEmpleadosRegistro/Views/Practica/Details.cshtml
@model ModelEmpleadosDepartamento

@{
    int numRegistros = 0;
    int posicion = 1;
    int dept = 0;
    if (ViewData["REGISTROS"] != null)
    {
        numRegistros = (int)ViewData["REGISTROS"];
        dept = (int)ViewData["DEPARTAMENTO"];
        posicion = (int)ViewData["POSICION"];
    }
}
<h1>Empleados Registro Departamento</h1>

<p>
	<a asp-controller="Practica" asp-action="Index">Volver a departamentos</a>
</p>

@if(Model != null){
	<ul class="list-group">
		<li class="list-group-item list-group-item-danger">IdDepartamento: @Model.Departamento.IdDepartamento</li>
        <li class="list-group-item list-group-item-info">Nombre: @Model.Departamento.Nombre</li>
        <li class="list-group-item list-group-item-info">Localidad: @Model.Departamento.Localidad</li>
	</ul>

	<h1>Registro @posicion de @Model.NumeroRegistros</h1>

    <div>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <a asp-controller="Practica" asp-action="Details" asp-route-idDepartamento="@dept" asp-route-posicion="1">Primero</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="Practica" asp-action="Details" asp-route-idDepartamento="@dept" asp-route-posicion="@ViewData["ANTERIOR"]">Anterior</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="Practica" asp-action="Details" asp-route-idDepartamento="@dept" asp-route-posicion="@ViewData["SIGUIENTE"]">Siguiente</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="Practica" asp-action="Details" asp-route-idDepartamento="@dept" asp-route-posicion="@ViewData["ULTIMO"]">Ultimo</a>
            </li>
        </ul>
    </div>
    <hr/>
    <ul class="list-group">
        @foreach (Empleado emp in Model.Empleado)
        {
            <li class="list-group-item list-group-item-info">
                Id Empleado: @emp.IdEmpleado
            </li>
            <li class="list-group-item list-group-item-info">
                Apellido: @emp.Apellido
            </li>
            <li class="list-group-item list-group-item-info">
                Oficio: @emp.Oficio
            </li>
            <li class="list-group-item list-group-item-info">
                Salario: @emp.Salario
            </li>
            <li class="list-group-item list-group-item-info">
                Departamento: @emp.IdDepartamento
            </li>
        }
    </ul>

}

MvcNetCorePrcaticaEmpleadosRegistro/Views/Practica/Index.cshtml
@model IEnumerable<MvcNetCorePrcaticaEmpleadosRegistro.Models.Departamento>

@{
    ViewData["Title"] = "Index";
}

<table class="table table-danger">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdDepartamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localidad)
            </th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDepartamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Localidad)
            </td>
            <td>
                <a asp-controller="Practica" asp-action="Details" asp-route-idDepartamento="@item.IdDepartamento" class="btn btn-outline-dark">Ver detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcNetCorePrcaticaEmpleadosRegistro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCorePrcaticaEmpleadosRegistro</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCorePrcaticaEmpleadosRegistro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCorePrcaticaEmpleadosRegistro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Practica" asp-action="Index">Departamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcNetCorePrcaticaEmpleadosRegistro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>